import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const handlers={},windowEvents={},viewportEvents={};
const node=()=>({hidden:false,textContent:'',value:'',style:{},attrs:{},handlers:{},
 setAttribute(k,v){this.attrs[k]=v;},removeAttribute(k){delete this.attrs[k];},
 addEventListener(k,f){this.handlers[k]=f;},contains(target){return target===this;},focus(){this.focused=true;}});
const trigger=node(),popup=node(),search=node(),list=node(),empty=node(),select=node();
trigger.getBoundingClientRect=()=>({top:100,bottom:145});
list.clientHeight=300;let markup='',options=[],scroll=0;
Object.defineProperty(list,'innerHTML',{get:()=>markup,set:text=>{
 markup=text;
 options=[...text.matchAll(/role="option" id="([^"]+)" data-index="(\d+)"/g)].map((match,position)=>{
  const option=node();option.id=match[1];option.dataset={index:match[2]};
  option.offsetTop=position*32+(text.slice(0,match.index).match(/role="group"/g)||[]).length*24;
  option.offsetHeight=32;option.classList={toggle(_name,value){option.active=value;}};
  option.closest=()=>option;return option;
 });
}});
Object.defineProperty(list,'scrollTop',{get:()=>scroll,set:v=>{scroll=Math.max(0,Math.min(v,(options.at(-1)?.offsetTop||0)+32-list.clientHeight));}});
list.querySelectorAll=()=>options;list.contains=target=>options.includes(target)||target===list;
popup.contains=target=>[popup,search,list,empty].includes(target)||options.includes(target);
const viewport={offsetTop:0,height:800,addEventListener:(k,f)=>viewportEvents[k]=f};
const context=vm.createContext({console,document:{addEventListener:(k,f)=>handlers[k]=f},innerHeight:800,visualViewport:viewport,addEventListener:(k,f)=>windowEvents[k]=f});context.window=context;
vm.runInContext(fs.readFileSync(new URL('concept-menu.js',import.meta.url),'utf8'),context);
const course=JSON.parse(fs.readFileSync(new URL('dist/curriculum.json',import.meta.url),'utf8'));
const rows=course.concepts.map(c=>({title:c.title,chapter:c.chapter,text:`${String(c.id).padStart(3,'0')} · ${c.title}`}));
const selected=[];
const menu=context.math2aiConceptMenu({select,trigger,popup,search,list,empty,onChoose:index=>{selected.push(index);menu.update(rows,index);}});
const gradient=rows.findIndex(r=>r.title==='Gradient descent');
const key=(key,target=search,extra={})=>{const event={key,preventDefault(){this.prevented=true;},...extra};target.handlers.keydown(event);return event;};
const type=value=>{search.value=value;search.handlers.input();};
const active=()=>Number(search.attrs['aria-activedescendant']?.split('-').at(-1));
const indices=()=>options.map(option=>Number(option.dataset.index));
menu.update(rows,gradient);assert.equal(select.hidden,true);assert.equal(trigger.hidden,false);
trigger.handlers.click();
assert.equal(trigger.attrs['aria-expanded'],'true');assert.equal(search.focused,true);
assert.equal(search.attrs['aria-expanded'],'true');assert.equal(active(),gradient);
assert.equal(options[gradient].offsetTop+16-list.scrollTop,150,'opening must center the current row');
assert.ok(options[gradient-2].offsetTop>=list.scrollTop);
assert.ok(options[gradient+2].offsetTop+32<=list.scrollTop+300);
key('ArrowDown');key('Escape');assert.equal(selected.length,0);assert.equal(popup.hidden,true);
key('ArrowDown',trigger);assert.equal(active(),gradient);
key('ArrowDown');key('Enter');assert.equal(selected.at(-1),gradient+1);assert.equal(popup.hidden,true);
key('End',trigger);assert.equal(active(),rows.length-1);key('ArrowDown');assert.equal(active(),rows.length-1);
key('Escape');key('Home',trigger);assert.equal(active(),0);key('ArrowUp');assert.equal(active(),0);
key('PageDown');assert.equal(active(),10);key('PageUp');assert.equal(active(),0);
assert.equal(key('End').prevented,undefined,'Home/End must keep native text editing');

// A middle substring must select the original concept, never its filtered index.
type('  oPaGa  ');const backprop=rows.findIndex(r=>r.title==='Backpropagation');
assert.deepEqual(indices(),[backprop]);assert.equal(active(),backprop);
const count=selected.length;key('Enter',search,{isComposing:true});assert.equal(selected.length,count);
key('Enter');assert.equal(selected.at(-1),backprop);assert.equal(popup.hidden,true);
assert.match(trigger.attrs['aria-label'],/Backpropagation/);
trigger.handlers.click();type('tention');
const attention=rows.map((r,i)=>r.title.toLowerCase().includes('tention')?i:-1).filter(i=>i>=0);
assert.deepEqual(indices(),attention);assert.equal(selected.length,count+1,'filtering must not navigate');
key('ArrowDown');assert.equal(active(),attention[1]);key('ArrowDown');assert.equal(active(),attention.at(-1));
type('no-such-concept');assert.equal(options.length,0);assert.equal(empty.hidden,false);
assert.equal(search.attrs['aria-activedescendant'],undefined);key('Enter');key('ArrowDown');
assert.equal(selected.length,count+1,'an empty result cannot select a hidden concept');
type('084');assert.equal(options.length,1);assert.equal(active(),83);
type('');assert.equal(options.length,rows.length);assert.equal(active(),backprop);assert.equal(empty.hidden,true);
assert.equal(options[backprop].offsetTop+16-list.scrollTop,150);
type('<script>');assert.equal(options.length,0);assert.ok(!markup.includes('<script>'));
key('Escape');key('g',trigger);assert.equal(search.value,'g');
assert.ok(indices().every(i=>rows[i].title.toLowerCase().includes('g')));
key('Escape');menu.update(rows,gradient);trigger.handlers.click();
const before=list.scrollTop;const updated=structuredClone(rows);updated[0].text+=' ✓';menu.update(updated,gradient);
assert.equal(list.scrollTop,before);assert.equal(active(),gradient);
type('tention');key('ArrowDown');const chosen=active();
updated[chosen].marker='Revisit later';menu.update(updated,gradient);
assert.equal(search.value,'tention');assert.equal(active(),chosen);assert.match(markup,/Revisit later/);

const previousSelections=selected.length;
assert.equal(key('Tab').prevented,undefined);popup.handlers.focusout({relatedTarget:{}});
assert.equal(selected.length,previousSelections);assert.equal(popup.hidden,true,'Tab leaves without choosing');
trigger.handlers.click();type('tention');list.handlers.click({target:options[1]});assert.equal(selected.at(-1),attention[1]);
assert.equal(popup.hidden,true);
trigger.handlers.click();handlers.pointerdown({target:search});assert.equal(popup.hidden,false);
handlers.pointerdown({target:{}});assert.equal(popup.hidden,true);
trigger.handlers.click();popup.handlers.focusout({relatedTarget:trigger});trigger.handlers.click();assert.equal(popup.hidden,true,'clicking the trigger closes the popup');
menu.update(rows,gradient);trigger.handlers.click();trigger.getBoundingClientRect=()=>({top:650,bottom:695});windowEvents.resize();
assert.equal(popup.style.top,'auto');assert.equal(popup.style.bottom,'calc(100% + 4px)');
trigger.getBoundingClientRect=()=>({top:100,bottom:145});viewport.height=330;viewportEvents.resize();
assert.equal(popup.style.maxHeight,'173px','fit above the mobile keyboard');
windowEvents.scroll();assert.equal(popup.hidden,false,'keyboard-induced page scrolling must not dismiss search');
key('Escape');assert.equal(search.value,'');assert.equal(search.attrs['aria-expanded'],'false');
const html=fs.readFileSync(new URL('site-template.html',import.meta.url),'utf8');
assert.ok(!html.includes('concept-label'));assert.ok(html.includes('aria-label="Search concepts"'));
console.log('PASS: middle-substring and number search, case/whitespace handling, filtered keyboard/mouse selection, empty results, IME, centering, live updates, focus dismissal, native fallback labels and mobile viewport placement.');
