// Pass the path to an installed @electric-sql/pglite/dist/index.js (test dependency only).
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
const {PGlite}=await import(process.argv[2] ? pathToFileURL(process.argv[2]).href : '@electric-sql/pglite');
const db=new PGlite();
const A='00000000-0000-4000-8000-000000000001',B='00000000-0000-4000-8000-000000000002';
await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
 grant usage on schema auth to anon,authenticated;
 insert into auth.users values ('${A}'),('${B}');
 create publication supabase_realtime;`);
const migration=fs.readFileSync(new URL('../supabase/migrations/202609140001_account_progress.sql',import.meta.url),'utf8');
await db.exec(migration);
const asUser=(user,fn,role='authenticated')=>db.transaction(async tx=>{
 await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[user||'']);
 await tx.exec('set local role '+role);return fn(tx);
});
const sync=(user,epoch,attempts=[],target=user)=>asUser(user,async tx=>(await tx.query('select public.math2ai_sync($1,$2,$3,$4) as data',[target,'2.0',epoch,JSON.stringify(attempts)])).rows[0].data);
const reset=(user,id)=>asUser(user,async tx=>(await tx.query('select public.math2ai_reset($1,$2,$3) as data',[user,'2.0',id])).rows[0].data);
const one={id:randomUUID(),question_id:'1-01',answer:2};
const two={id:randomUUID(),question_id:'5-01',answer:1};
assert.equal((await sync(A,null)).epoch,0);
await Promise.all([sync(A,0,[one]),sync(A,0,[two])]);
const both=await sync(A,0,[one]);assert.equal(Object.keys(both.answers).length,2);assert.equal(both.answers['1-01'].attempts,1);
await sync(A,0,[{id:randomUUID(),question_id:'1-01',answer:0}]);
const wrong=await sync(A,0);assert.equal(wrong.answers['1-01'].choices,5);assert.equal(wrong.answers['1-01'].attempts,2);
assert.equal(Object.keys((await sync(B,null)).answers).length,0);
assert.equal((await asUser(B,tx=>tx.query('select * from public.math2ai_answers'))).rows.length,0);
assert.equal((await asUser(B,tx=>tx.query('select * from public.math2ai_progress'))).rows.length,1);
await assert.rejects(sync(B,0,[one],A),/Not authorized/);
await assert.rejects(asUser(null,tx=>tx.query('select public.math2ai_sync($1,$2)',[A,'2.0']),'anon'),/permission denied/);
await assert.rejects(asUser(A,tx=>tx.query('delete from public.math2ai_answers')),/permission denied/);
await assert.rejects(asUser(A,tx=>tx.query('update public.math2ai_progress set epoch=99')),/permission denied/);
await assert.rejects(sync(A,0,[{...one,id:randomUUID(),answer:9}]),/Invalid answer/);
await assert.rejects(sync(A,0,Array(101).fill(one)),/Batch too large/);
console.log('PASS: real PostgreSQL migration, merged answers, idempotent retries, input validation, owner-only reads and RPC writes; guest and cross-account access denied.');
const request=randomUUID(),cleared=await reset(A,request);assert.equal(cleared.epoch,1);assert.deepEqual(cleared.answers,{});
assert.deepEqual((await sync(A,0,[{...one,id:randomUUID()}])).answers,{});
await sync(A,1,[{...two,id:randomUUID()}]);
const again=await reset(A,request);assert.equal(again.epoch,1);assert.equal(Object.keys(again.answers).length,1);
assert.equal((await sync(B,0)).epoch,0);
console.log('PASS: atomic reset rejects stale epochs; retrying an acknowledged reset cannot delete newer answers.');
const beforeReapply=await sync(A,1);
await db.exec(migration);
assert.deepEqual(await sync(A,1),beforeReapply);
assert.deepEqual(await reset(A,request),beforeReapply);
assert.equal((await asUser(B,tx=>tx.query('select * from public.math2ai_answers'))).rows.length,0);
await assert.rejects(sync(B,0,[one],A),/Not authorized/);
console.log('PASS: reapplying setup preserves answers, reset epochs, operation deduplication and account isolation.');
assert.equal((await db.query("select count(*)::int as n from pg_publication_tables where pubname='supabase_realtime' and tablename='math2ai_progress'")).rows[0].n,1);
await db.close();
