import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
const {PGlite}=await import(process.argv[2]?pathToFileURL(process.argv[2]).href:'@electric-sql/pglite');
const db=new PGlite(),A='00000000-0000-4000-8000-000000000001',B='00000000-0000-4000-8000-000000000002';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
 grant usage on schema auth to anon,authenticated;insert into auth.users values('${A}'),('${B}');create publication supabase_realtime;`);
const oldMigration=fs.readFileSync(new URL('../supabase/migrations/202609140001_account_progress.sql',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migrations/202609200001_learning_choices.sql',import.meta.url),'utf8');
await db.exec(oldMigration);
const asUser=(user,fn,role='authenticated')=>db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[user||'']);await tx.exec('set local role '+role);return fn(tx);});
const answers=()=>asUser(A,async tx=>(await tx.query('select public.math2ai_sync($1,$2,$3,$4) as data',[A,'2.0',0,JSON.stringify([{id:'00000000-0000-4000-8000-000000000003',question_id:'1-01',answer:2}])])).rows[0].data);
const before=await answers();await db.exec(migration);
const sync=(user,changes=[],target=user,version='2.0')=>asUser(user,async tx=>(await tx.query('select public.math2ai_learning_sync($1,$2,$3) as data',[target,version,JSON.stringify(changes)])).rows[0].data);
const op=(key,value,base=0,parent=null)=>({id:randomUUID(),key,value,base,parent});
assert.deepEqual(await answers(),before);
const bookmark=op('concept:1','revisit'),second=op('concept:4','revisit');
let saved=await sync(A,[bookmark,second]);assert.equal(saved.fields['concept:1'].value,'revisit');assert.equal(saved.revision,2);
saved=await sync(A,[bookmark]);assert.equal(saved.revision,2);assert.deepEqual(saved.accepted,[bookmark.id]);
const remove=op('concept:1','none',1),stale=op('concept:1','revisit',1);
saved=await sync(A,[remove]);saved=await sync(A,[stale]);assert.equal(saved.fields['concept:1'].value,'none');assert.deepEqual(saved.conflicts,[stale.id]);
const next=op('concept:2','revisit'),then=op('concept:2','none',0,next.id);
saved=await sync(A,[next,then]);assert.equal(saved.fields['concept:2'].value,'none');
// Different fields merge even if a device's global revision was stale.
const distinct=op('concept:3','revisit');saved=await sync(A,[distinct]);assert.equal(saved.fields['concept:2'].value,'none');
assert.equal(saved.fields['concept:3'].value,'revisit');assert.deepEqual(await answers(),before);
assert.deepEqual((await sync(B)).fields,{});assert.deepEqual((await sync(A,[],A,'other')).fields,{});
assert.equal((await asUser(B,tx=>tx.query("select * from public.math2ai_learning where user_id=$1",[A]))).rows.length,0);
await assert.rejects(sync(B,[bookmark],A),/Not authorized/);
await assert.rejects(sync(A,[],null),/Not authorized/);
await assert.rejects(asUser(null,tx=>tx.query('select public.math2ai_learning_sync($1,$2)',[A,'2.0']),'anon'),/permission denied/);
await assert.rejects(asUser(A,tx=>tx.query('update public.math2ai_learning set fields=\'{}\'')),/permission denied/);
await assert.rejects(asUser(A,tx=>tx.query('delete from public.math2ai_learning')),/permission denied/);
for(const bad of [op('concept:0','revisit'),op('concept:129','revisit'),op('concept:1','done'),op('concept:1','mastered'),op('example-domain','mineral'),op('private','none'),op('concept:1','none',-1),{...bookmark,base:null},{...bookmark,id:null},op('concept:1','revisit',0.5)])await assert.rejects(sync(A,[bad]));
await assert.rejects(sync(A,Array(101).fill(bookmark)),/Batch too large/);
await assert.rejects(sync(A,null),/Invalid changes/);
const check=await sync(A);await db.exec(migration);assert.deepEqual(await sync(A),check);assert.deepEqual(await answers(),before);
assert.equal((await db.query("select count(*)::int as n from pg_publication_tables where pubname='supabase_realtime' and tablename='math2ai_learning'")).rows[0].n,1);
console.log('PASS: actual PostgreSQL migration; private account/course state; owner-only RPC writes; per-field conflict checks; ordered offline changes; idempotent retries; validation; reapplication; quiz progress untouched.');
await db.close();
