// Exercise the actual chooser, practice handlers and answer journal together.
import assert from 'node:assert/strict';
import {bootBrowser,hub,course,flush,Server} from './progress-test-helpers.mjs';
const boot=async options=>{const app=bootBrowser(options);await flush();return app;};
const [scalar,variable,fn]=course.concepts;
const savedView=app=>[...app.storage.entries()].filter(([k])=>k.endsWith(':guest:view')).map(([,v])=>JSON.parse(v))[0];
const row=(app,c)=>app.get('review-topics').innerHTML.split('<tr>').find(s=>s.includes(`id="review-topic-${c.legacyId}"`))||'';
const chosen=(app,c)=>new RegExp(`value="${c.legacyId}"[^>]* checked`).test(row(app,c));
const count=app=>app.get('review-selection-count').textContent;
const stats=(app,c)=>[...row(app,c).matchAll(/<td><span[^>]*>[^<]*<\/span>([^<]*)<\/td>/g)].map(m=>m[1]);

const fresh=await boot();const first=fresh.question().id;
fresh.review();
assert.equal(fresh.get('review-chooser').hidden,false);
assert.equal(fresh.get('quiz-panel').hidden,true,'Review opens the overview, not a question');
assert.equal((fresh.get('review-topics').innerHTML.match(/name="review-topic"/g)||[]).length,128);
assert.equal((fresh.get('review-topics').innerHTML.match(/class="review-chapter"/g)||[]).length,course.chapters.length);
assert.deepEqual(stats(fresh,scalar),['0/10','—','—']);
assert.match(row(fresh,scalar),/Not tried/);assert.doesNotMatch(row(fresh,scalar),/Looking solid|Worth revisiting/);
assert.equal(chosen(fresh,scalar),true,'new learner defaults to the current concept');
fresh.clearTopics();assert.equal(fresh.get('review-start').disabled,true);fresh.startReview();
assert.equal(fresh.get('quiz-panel').hidden,true);
fresh.selectTopic(variable.legacyId);fresh.startReview();
assert.equal(fresh.get('quiz-panel').hidden,false,'an untried selected concept is available');
assert.ok(variable.questions.some(q=>q.id===fresh.question().id));
fresh.correct();fresh.back();assert.equal(fresh.question().id,first);
console.log('PASS: all chapters/topics, neutral untried stats, explicit selection, disabled empty start, and practice of untried topics.');

const app=await boot();
app.wrong();app.retry();app.correct();app.another();app.correct();app.another();app.correct();
app.review();assert.deepEqual(stats(app,scalar),['3/10','2/3','3/3']);
assert.doesNotMatch(row(app,scalar),/Looking solid/);
app.back();app.another();app.correct();app.another();
app.go(1);app.wrong();const missed=app.question();
app.go(0);const lesson=app.question();app.draft(2);app.scroll(540);const before=savedView(app);
app.review();
assert.deepEqual(stats(app,scalar),['4/10','3/4','4/4']);assert.match(row(app,scalar),/Looking solid/);
assert.deepEqual(stats(app,variable),['1/10','0/1','0/1']);assert.match(row(app,variable),/Worth revisiting/);
assert.equal(chosen(app,variable),true);assert.equal(chosen(app,scalar),false,'suggestions prioritize latest mistakes');
app.selectTopic(scalar.legacyId);assert.equal(count(app),'2 topics selected');
app.filterReview('solid');assert.ok(row(app,scalar));assert.equal(row(app,variable),'');assert.equal(count(app),'2 topics selected');
app.searchReview('no such topic');assert.equal(app.get('review-no-matches').hidden,false);
assert.equal(count(app),'2 topics selected');assert.equal(app.get('review-start').disabled,false,'hidden selections stay available');
app.startReview();assert.equal(app.question().id,missed.id);assert.equal(app.get('feedback').hidden,true);
app.correct();app.correct();assert.equal(app.state().concepts[variable.legacyId].answers[missed.id].attempts,2);
assert.deepEqual(savedView(app),before,'selection and review answers never replace lesson navigation');
const seen=new Set([missed.id]);
for(let i=0;i<19;i++){
 app.another();const q=app.question();assert.ok(!seen.has(q.id));seen.add(q.id);
 assert.ok([scalar,variable].some(c=>c.questions.some(x=>x.id===q.id)),'selection bounds every question');
 if(i===0)assert.ok(scalar.questions.some(x=>x.id===q.id),'mix concepts rather than exhausting one');
}
const last=app.question().id;app.another();assert.notEqual(app.question().id,last);
app.back();assert.equal(app.question().id,lesson.id);assert.match(app.get('choices').innerHTML,/value="2" checked/);
assert.equal(app.scrollPosition(),540);assert.deepEqual(savedView(app),before);
console.log('PASS: first/latest denominators, strengths, filtered-out choices, selected-pool rotation, exact lesson/deck/draft/scroll return.');

app.review();app.clearTopics();app.searchReview('scalar');app.selectChapter(0);
assert.equal(count(app),'1 topic selected');assert.equal(chosen(app,scalar),true,'chapter selection respects search');
app.selectChapter(0);assert.equal(count(app),'0 topics selected');
app.searchReview('');app.selectChapter(0);
const chapterSize=course.concepts.filter(c=>c.chapter===scalar.chapter).length;
assert.equal(count(app),`${chapterSize} topics selected`);app.selectChapter(0);assert.equal(count(app),'0 topics selected');
app.selectTopic(fn.legacyId);app.filterReview('selected');assert.ok(row(app,fn));assert.equal(row(app,scalar),'');
app.selectTopic(fn.legacyId,false);assert.equal(app.get('review-no-matches').hidden,false);
app.filterReview('all');app.suggestTopics();
assert.equal(chosen(app,scalar),true);assert.equal(chosen(app,variable),true,'with no latest mistakes, suggest practiced topics');
app.clearTopics();app.selectTopic(fn.legacyId);app.startReview();const draft=app.question();app.draft(1);
app.changeTopics();assert.equal(app.get('quiz-panel').hidden,true);assert.equal(app.get('review-start').textContent,'Resume review');
app.startReview();assert.equal(app.question().id,draft.id);assert.match(app.get('choices').innerHTML,/value="1" checked/);
app.answer(draft.correct);app.changeTopics();app.startReview();assert.equal(app.get('feedback').hidden,false);
app.changeTopics();app.clearTopics();app.selectTopic(variable.legacyId);assert.equal(app.get('review-start').textContent,'Start review');
app.startReview();assert.ok(variable.questions.some(q=>q.id===app.question().id));assert.equal(app.get('feedback').hidden,true);
app.back();app.review();assert.equal(count(app),'1 topic selected');assert.equal(chosen(app,variable),true);
const reload=await boot({shared:hub(app.storage),hash:'#review'});
assert.equal(reload.get('review-chooser').hidden,false);assert.equal(chosen(reload,variable),true);
reload.hash('#lesson-'+fn.legacyId);assert.equal(reload.current().legacyId,fn.legacyId);
reload.review();reload.hash('');assert.equal(reload.get('review-panel').hidden,true);
console.log('PASS: chapter scope, presets, change/resume preserves drafts and feedback, changed scope restarts, selection survives reopening/reload.');

const shared=hub(),left=await boot({shared}),right=await boot({shared});
left.wrong();await flush();right.review();right.clearTopics();right.selectTopic(variable.legacyId);
left.retry();left.correct();await flush();
assert.deepEqual(stats(right,scalar),['1/10','0/1','1/1']);assert.equal(chosen(right,variable),true);assert.equal(chosen(right,scalar),false);
right.startReview();right.draft(3);left.go(1);left.correct();await flush();
assert.match(right.get('choices').innerHTML,/value="3" checked/);
await left.reset();await flush();right.changeTopics();
assert.deepEqual(stats(right,scalar),['0/10','—','—']);assert.deepEqual(stats(right,variable),['0/10','—','—']);
assert.equal(chosen(right,variable),true,'clear answers does not manufacture or erase topic preferences');
right.back();assert.deepEqual(right.state().concepts[scalar.legacyId].answers,{});
console.log('PASS: live stats retain selections/drafts; remote reset removes statistics without resurrecting data.');

const server=new Server(),account=await boot({configured:true});
account.signin(server,'A');await flush();account.wrong();await flush();const accountQ=account.question();
account.review();account.startReview();account.correct();await flush();
assert.equal(server.data('A',course.version).answers[accountQ.id].last,accountQ.correct);
account.changeTopics();account.clearTopics();account.selectTopic(variable.legacyId);account.selectTopic(fn.legacyId);
const other=await boot({configured:true});other.signin(server,'A');await flush();other.review();
assert.deepEqual(stats(other,scalar),['1/10','0/1','1/1']);
account.signout();assert.equal(account.get('review-panel').hidden,true);await flush();account.review();
assert.deepEqual(stats(account,scalar),['0/10','—','—']);assert.equal(count(account),'1 topic selected');
account.signin(server,'B');await flush();account.review();assert.equal(count(account),'1 topic selected');
assert.deepEqual(stats(account,scalar),['0/10','—','—']);
account.signin(server,'A');await flush();account.review();assert.equal(count(account),'2 topics selected');
assert.equal(chosen(account,variable),true);assert.equal(chosen(account,fn),true);
await account.reset();assert.equal(account.get('review-panel').hidden,true);assert.deepEqual(account.state().concepts[scalar.legacyId].answers,{});
console.log('PASS: account sync, private selections, sign-out/account switching/reset isolation.');

const loading=await boot({configured:true});loading.review();assert.equal(loading.get('review-loading').hidden,false);
assert.equal(loading.get('review-start').disabled,true);loading.signin(server,'A');await flush();
assert.equal(loading.get('review-chooser').hidden,false);assert.equal(loading.get('review-loading').hidden,true);
const canceled=await boot({configured:true});canceled.review();canceled.back();canceled.signin(server,'A');await flush();
assert.equal(canceled.get('review-panel').hidden,true);
const blocked=await boot({readBlocked:true,writeBlocked:true});blocked.wrong();blocked.review();blocked.startReview();blocked.correct();blocked.back();
assert.equal(blocked.get('concept-score').hidden,false);assert.match(blocked.get('storage-note').textContent,/cannot save/);
blocked.review();blocked.clearTopics();blocked.selectTopic(fn.legacyId);blocked.back();blocked.review();assert.equal(chosen(blocked,fn),true);
console.log('PASS: loading/navigation races and blocked storage preserve the chooser and in-memory selection.');
