"""Independent calculations for the added question bank (standard library only)."""
from pathlib import Path
from fractions import Fraction
import json, math, re
course = json.loads((Path(__file__).parent/'dist/curriculum.json').read_text(encoding='utf-8'))
by_title = {c['title']:c for c in course['concepts']}
# Match a unique authored prompt, then compare its selected answer with a fresh calculation.
cases = [
 ('Borehole logs and assays','from 40 m to 42.5 m',42.5-40),
 ('Geoscience data integration','10,000 grams per tonne',10000/1000000*100),
 ('Ore grade estimation','8 tonnes of copper',8*.75),
 ('Ore grade estimation','Equal masses',(1+3)/2),
 ('Ore grade estimation','100 tonnes at 1%',(100*.01+300*.03)/(100+300)*100),
 ('Variable','makes 3x − 2 = 13',(13+2)/3),
 ('Variable','b = −1',-1+3),
 ('Function','f(−2)',(-2)**2),
 ('Function','f(g(3))',2*3+1),
 ('Units','250 centimetres',250/100),
 ('Units','1 kilometre plus',1000+500),
 ('Vector','dimension of (8',len([8,0,-1,2])),
 ('Matrix','entries are in a 4',4*3),
 ('Matrix','A₁₂ + A₂₁',[[2,7],[8,1]][0][1]+[[2,7],[8,1]][1][0]),
 ('Tensor','shape (3, 2, 5)',math.prod([3,2,5])),
 ('Summation','Σᵢ₌₁³ 2',sum(2 for _ in range(3))),
 ('Summation','Σᵢ₌₂⁴ i',sum(range(2,5))),
 ('Summation','xᵢ = 20',20/4),
 ('Summation','x = (2, −2, 5)',sum([2,-2,5])),
 ('Summation','Σᵢ₌₀⁴',len(range(5))),
 ('Dot product','(2, −1) · (3, 4)',sum(x*y for x,y in zip([2,-1],[3,4]))),
 ('Dot product','x · x for',sum(x*x for x in [3,4])),
 ('Dot product','(1, 0) · (8, 9)',1*8+0*9),
 ('Euclidean distance','(0, 0) and (0, 6)',math.dist([0,0],[0,6])),
 ('Euclidean distance','norm of (−6, −8)',math.hypot(-6,-8)),
 ('Euclidean distance','squared Euclidean distance',sum((x-y)**2 for x,y in zip([-2,1],[2,3]))),
 ('Probability','P(not A)',1-.3),
 ('Probability','P(two heads)',.5*.5),
 ('Probability','0.2, 0.5, and p',1-.2-.5),
 ('Probability','Two events cannot happen together',.2+.3),
 ('Conditional probability','P(A and B) = 0.2',.2/.5),
 ('Conditional probability','Among 20 samples',2/8),
 ('Conditional probability','P(A given B) = 0.6',.6*.5),
 ('Expected value','coin pays 6',.5*6+.5*0),
 ('Expected value','E[2X + 1]',2*3+1),
 ('Expected value','costs 5',4-5),
 ('Expected value','outcomes 2 and 10',2*.75+10*.25),
 ('Variance','variance is 9',math.sqrt(9)),
 ('Variance','Var(3X)',3**2*2),
 ('Variance','values −2 and 8',sum((x-3)**2 for x in [-2,8])/2),
 ('Exponential and logarithm','log₂(16)',math.log2(16)),
 ('Exponential and logarithm','ln(1)',math.log(1)),
 ('Exponential and logarithm','2⁻³',2**-3),
 ('Exponential and logarithm','doubles five times',2**5),
 ('Exponential and logarithm','ln(e⁵)',math.log(math.exp(5))),
 ('Derivative','f′(0)',2*0),
 ('Derivative','increase of 0.01',5*.01),
 ('Derivative','f′(2)',3*2**2),
 ('Integral','∫₂⁶ 3',3*(6-2)),
 ('Integral','∫₂²',0),
 ('Integral','∫₀² t',2**2/2),
 ('Chain rule','(x + 1)²',2*(2+1)),
 ('Chain rule','dy/du = 4',4*3),
 ('Chain rule','derivatives 2, 3, and 4',math.prod([2,3,4])),
 ('Optimization','(x − 2)²',min(range(-5,6),key=lambda x:(x-2)**2)),
 ('Optimization','maximizes 5 − x',max([1,2,3],key=lambda x:5-x)),
 ('Gradient descent','θ = 2, gradient = −3',2-.1*(-3)),
 ('Gradient descent','L(θ) = θ²',1-.25*(2*1)),
 ('Dataset and features','12 samples with 3',12*3),
 ('Linear regression','3x − 2',3*4-2),
 ('Linear regression','w = (2, 1)',2*3+1*4),
 ('Mean squared error','errors 0 and 4',(0**2+4**2)/2),
 ('Mean squared error','predictions (1,7)',sum((a-b)**2 for a,b in zip([1,7],[3,3]))/2),
 ('Mean squared error','metres to centimetres',100**2),
 ('Normalization','x = 8',(8-10)/2),
 ('Normalization','z = 2, μ = 5',5+3*2),
 ('Artificial neuron','inputs (1, 2)',1*3+2*4-1),
 ('Artificial neuron','weighted sum of −4',max(0,-4)),
 ('Sigmoid','σ(z) = 0.3',.3*(1-.3)),
 ('Sigmoid','σ(z) = 0.8',1-.8),
 ('ReLU','ReLU(5)',max(0,5)),
 ('ReLU','ReLU change',next(x for x in [-6,0,4,9] if max(0,x)!=x)),
 ('Forward pass','ŷ = 3x + 1',3*2+1),
 ('Forward pass','h = ReLU(2x − 5)',max(0,2*2-5)),
 ('Backpropagation','x = 2, w = 1',2*(1*2-3)*2),
 ('Mini-batch gradient descent','gradients −3, 3, and 12',sum([-3,3,12])/3),
 ('Mini-batch gradient descent','θ = 5',5-.1*2),
 ('Epoch','10 samples and batch size 4',math.ceil(10/4)),
 ('Epoch','100 samples and batch size 10',3*math.ceil(100/10)),
 ('Regularization','w = (−2,5)',(-2)**2+5**2),
 ('Regularization','data loss 2',2+.5*4),
 ('Softmax','three equal logits',1/3),
 ('Softmax','z₁ − z₂ = ln(2)',math.exp(math.log(2))),
 ('Cross-entropy','−ln(1)',-math.log(1)),
 ('Cross-entropy','ptrue = 1/e',-math.log(1/math.e)),
 ('Embedding','100 objects and 8',100*8),
 ('Cosine similarity','(3,4) and (4,3)',(3*4+4*3)/(math.hypot(3,4)*math.hypot(4,3))),
 ('Cosine similarity','(1, 0) and (−1, 0)',-1/(1*1)),
 ('Principal component analysis','20 features are projected onto 3',3),
 ('Bit and byte','3 bits encode',2**3),
 ('Bit and byte','bits are in 4 bytes',4*8),
 ('Bit and byte','16 distinct fixed-length IDs',math.ceil(math.log2(16))),
 ('Bit and byte','sequence of 5 bits',2**5),
 ('Bit and byte','10 distinct symbols',math.ceil(math.log2(10))),
 ('Bit and byte','100 values at 16 bits',100*16/8),
 ('Numerical precision','4.567 is represented as 4.57',abs(4.567-4.57)),
 ('Numerical precision','100 is approximated by 99',abs(100-99)),
 ('Rate-distortion tradeoff','D = 2, R = 4',2+.5*4),
 ('Vector quantization','codebook {0, 5, 10}',min([0,5,10],key=lambda v:(v-6)**2)),
 ('Token and vocabulary','vocabulary of 32',math.ceil(math.log2(32))),
 ('Vector-quantized autoencoder','4 IDs from a 16-entry',4*math.ceil(math.log2(16))),
 ('Sequence and autocorrelation','length-6 sequence',6-2),
 ('Sequence and autocorrelation','lag zero',1),
 ('Autoregressive language model','conditional probabilities 0.6, 0.5, and 0.2',.6*.5*.2),
 ('Scaled dot-product attention','weights (0.5, 0.5)',.5*2+.5*8),
 ('Multi-head attention','four heads each output width 8',4*8),
 ('Dynamical system','sₜ = 4, aₜ = −1',4-1),
 ('Dynamical system','initial state 8',8*.5**2),
 ('Reward and return','rewards 2, 4, and 8',sum(.5**i*r for i,r in enumerate([2,4,8]))),
 ('Reward and return','rewards −1 and 4',-1+.5*4),
 ('Policy','probabilities 0.7 and p',1-.7),
 ('Value function','returns 2 and 8',sum([2,8])/2),
 ('Value function','valued at 4 and 10',.75*4+.25*10),
 ('Bellman equation','reward 2, γ = 0.5',2+.5*6),
 ('Bellman equation','next values 2 and 6',1+.5*((2+6)/2)),
 ('Exploration and exploitation','ε = 0.2 with uniform',.8+.2/2),
 ('Q-learning','r = 2, γ = 0.5',2+.5*8),
 ('Q-learning','old Q = 4',4+.5*(10-4)),
 ('Policy gradient','θ = 1, η = 0.2',1+.2*3),
 ('Policy gradient','P(A) = 0.6',.6*4+.4*1),
 ('Policy gradient','dJ/dp',2-5),
 ('RLHF','answer rewards 3 and 1',.25*3+.75*1),
 ('CPU','running sum',sum([2,3,5])),
 ('Tensor core','A = 3, B = 4',3*4+2),
 ('CUDA','block index 2',2*128+5),
 ('CUDA','4 blocks of 64',4*64),
 ('Memory capacity','1,000 parameters',1000*32/8),
 ('Memory capacity','2 billion parameters',2*2),
 ('Memory bandwidth','80 GB/s',24/80),
 ('Memory bandwidth','60 GB/s effective',21/60),
 ('H100','4-byte values',80/4),
 ('Compute cluster','time = 2 + 8/n',2+8/4),
 ('TSMC and chip fabrication','210 of 250',100*210/250),
 ('TSMC and chip fabrication','200 dies',200*.75),
 ('Windowing and missing data','length 8, window length 3',8-3+1),
 ('Benchmark and ablation','18 of 20',100*18/20),
 ('Benchmark and ablation','full system scores 0.86',.86-.74),
 ('Forward-deployed engineering','20 minutes to 12',20-12),
]
for title, fragment, expected in cases:
 matches = [q for q in by_title[title]['questions'][1:] if fragment in q['question']]
 assert len(matches)==1, (title,fragment,len(matches))
 q=matches[0]; label=q['options'][q['correct']].replace('−','-').replace(',','')
 token=re.search(r'-?[\d.]+(?:/[\d.]+)?',label)
 assert token, (title,fragment,label)
 actual=float(Fraction(token.group()))
 assert math.isclose(actual,expected,rel_tol=1e-10,abs_tol=1e-10), (title,fragment,actual,expected)
# Check some structured answers without interpreting their labels as scalars.
structured = [
 ('Vector','(1, 2) + (3, 4)',str(tuple(a+b for a,b in zip((1,2),(3,4))))),
 ('Vector','(5, 1) − (2, 4)',str(tuple(a-b for a,b in zip((5,1),(2,4))))),
 ('Gradient','∇L(1, −2)',str((2*1,2*-2))),
 ('Gradient','∇L(2, 3)',str((3,2))),
 ('Matrix multiplication','[[1, 2]] multiplied',str([[1*3+2*4]])),
 ('Matrix multiplication','[[2, 0], [0, 3]] times',str([[2*4],[3*5]])),
 ('Transpose','[[1, 2], [3, 4]]ᵀ',str([list(row) for row in zip(*[[1,2],[3,4]])])),
 ('ReLU','(−1, 0, 2)',str(tuple(max(0,x) for x in (-1,0,2)))),
 ('Provenance and uncertainty','reading 10',str([10-2,10+2])),
]
for title, fragment, expected in structured:
 matches=[q for q in by_title[title]['questions'][1:] if fragment in q['question']]
 assert len(matches)==1,(title,fragment)
 q=matches[0];actual=q['options'][q['correct']].replace('−','-')
 assert actual==expected,(title,actual,expected)
print(f'PASS: {len(cases)+len(structured)} independently calculated new numerical/structured answers.')
